### ISSUE TITLE
Exception in Rider 2024

### ISSUE THREAD

**Issue by timurproko** [Noorts/Toggler#68]
I starting to get errors like this after installing Rider 2024
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'core.ToggleAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.noorts.toggler]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:200)

```

**Comment by Noorts** [comment]
Hey @timurproko, thanks for the report!

The latest update (Toggler v1.4.0) should have resolved this deprecation (see [this](https://github.com/Noorts/Toggler/issues/64) issue). Could you please confirm that the Toggler version you are running is v1.4.0?

If you are already running Toggler v1.4.0 and the error remains, could you please specify the exact Rider version you are using and potentially your platform (OS) as well? This would greatly help me reproduce the issue. Thanks!

**Comment by timurproko** [comment]
I was previously using version Toggler-1.3.1, I've updated to Toggler-1.4, and I'm pleased to report that the issue has been resolved. I apologize for any inconvenience caused and want to express my gratitude for your diligent efforts!

**Comment by Noorts** [comment]
No worries! Again, thanks for reporting!
